### ISSUE TITLE
use doc too less

### ISSUE THREAD

**Issue by lifehacking** [motiv-labs/janus#100]
config:
  
  "proxy": {
        "append_listen_path": false, 
        "check_host_against_uptime_tests": false, 
        "enable_load_balancing": false, 
        "listen_path": "/vvvv", 
        "methods": [
            "GET"
        ], 
        "preserve_host_header": false, 
        "strip_listen_path": true, 
        "target_list": [], 
        "target_url": "http://172.31.68.243/app/"

access:
http  http://172.31.68.244:8080/vvvv

result:
HTTP/1.1 404 Not Found
Content-Length: 19
Content-Type: text/plain; charset=utf-8
Date: Mon, 13 Mar 2017 08:46:34 GMT
X-Content-Type-Options: nosniff

404 page not found

but can access:
curl http://172.31.68.243/app/

**Comment by lifehacking** [comment]
when in debug mode,can not see any error access log，Only see success access log
export DEBUG=true
export LOG_LEVEL="debug"

**Comment by italolelis** [comment]
Hello @lifehacking,

I am sorry but I really didn't understand what was the problem... Did you configure an API and got a 404? If that's the case just look at this #84 and #95.

If that's not the problem could you elaborate a bit more on what you're facing?

Thank you.

**Comment by lifehacking** [comment]
thank you！！！，after restart janus，now works

**Comment by italolelis** [comment]
Cool, I'm closing this issue then!
