### ISSUE TITLE
Wrong location is redirect response

### ISSUE THREAD

**Issue by olvlvl** [motiv-labs/janus#102]
We get a redirect response when the URI has a trailing slash, but the `Location` header and the link in the body are wrong. For instance when I query <https://api-v2.hellofresh.com/menus/?week=2016-W45&country=DE> I get the following response:

```
HTTP/1.1 301 Moved Permanently
Server: nginx/1.10.0 (Ubuntu)
Date: Fri, 17 Mar 2017 13:52:38 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 74
Connection: close
Location: /api/menus?week=2016-W45&country=DE
Strict-Transport-Security: max-age=31536000

<a href="/api/menus?week=2016-W45&amp;country=DE">Moved Permanently</a>.
```

Also, I don't know where `api` is coming from :(

**Expected behavior:**

The `Location` header and the link should be `https://api-v2.hellofresh.com/menus?week=2016-W45&country=DE`

**Observed behavior:**

The `Location` header and the link are `/api/menus?week=2016-W45&amp;country=DE`

**Comment by kieranajp** [comment]
This is because of the internal hacks required to support HF apiv2, now that we're using the GW properly internally I'm sure this makes more sense. It's not something relevant to this in an OSS context.
