### ISSUE TITLE
[Feature request] Modify proxied headers

### ISSUE THREAD

**Issue by pavlepredic** [motiv-labs/janus#145]
Please add support for filtering specific headers when proxying to `upstream_url`. The use case is running janus in development environment, where it is used to proxy requests to staging services. In this scenario, the `Authorization` header proxied by janus will be incorrect for the staging environment. The solution would be to add something like:
```
"headers": [
        "Authorization": null, //example of header removal
        "User-Agent": "Janus" //example of header modification
    ]
```
to the API configuration on janus. This will cover a much wider use case (not only filtering, but also adding and modifying headers). The assumption is that specifying `null` signals to janus to remove this header.

**Comment by italolelis** [comment]
Solved on #150
