### ISSUE TITLE
it will be better to mention install HTTPie to use http in mac cli in readme.MD

### ISSUE THREAD

**Issue by gene-point** [motiv-labs/janus#165]
it will be better to mention install HTTPie to use http in mac cli in readme.MD

i tried the curl and some other tools and failed, later HTTPie worked.

**Comment by italolelis** [comment]
Yes, we can mention that. 
But all requests also works with `curl`... you just have to change it to the `curl` format :)

**Comment by gene-point** [comment]
Thanks:)
