### ISSUE TITLE
Adding custom proxy to be hit on every request

### ISSUE THREAD

**Issue by michaeltcoelho** [motiv-labs/janus#181]
I would like to add a custom proxy to be hit on every request, is it possible in Janus? Is there any options for adding a custom `middleware`?

Thanks in advance.

**Comment by italolelis** [comment]
Hi @michaeltcoelho,

At the moment you can't have a custom plugin out of the box. You would have to fork this project, write your plugin and compile it.  We are working on something that will allow you to have custom plugins soon.

Sorry for this.

**Comment by michaeltcoelho** [comment]
Thanks @italolelis for replying! 

I will think about forking and creating a middleware for what i need to.

If you guys need some help on developing this feature, please, reach out to me.

**Comment by michaeltcoelho** [comment]
Hey @italolelis ,  

I've forked janus at [iclinic/janus](https://github.com/iclinic/janus), i'm writing my middleware into `pkg/plugin/auth`, but when compiling it it is not working, my middleware is not being called. So, i had to change all import from `github.com/hellofresh/janus/**` to my forked one `github.com/iclinic/janus/**` and it worked. 

I know that that is not the right way of doing it, when you guys make a new release i will have problem with it.

Can you guy give me some tips about it?

Thanks in advance!

**Comment by mario-mazo** [comment]
@michaeltcoelho clone your fork ``iclinic/janus`` into ``$GOPATH/src/github.com/hellofresh/janus`` and add a remote to  upstream  ``hellofresh/janus``. Anyway I am interested in doing something similar, I need to add something to a JWT (actually create a different one) when inbound and remove it outbound so I can have something like outside JWT and inside JWT, still not sure about how to do this. hopefully we can share ideas

**Comment by italolelis** [comment]
Hey @michaeltcoelho (vc é Brasileiro mano? haha) what @mariomazo said works fine for a forked repo, let us know if that works for you.

I wanted to implement the `go` dynamic plugin loading to make sure you guys wouldn't have to fork the repo to implement you own middlewares :/
Unfortunately `go` dynamic plugins only work for Linux distributions at the moment, which is holding me back a bit in implementing this. We can also discuss a different approach for this if you guys have any ideas

**Comment by mario-mazo** [comment]
@italolelis do you have any tips for my goal? I am here in Berlin also, if you want we can talk about it over beers/coffee/pizza (of course on me). I saw you gave the tutorial for women who go, but well... I was not allowed to go, let me know if we can work something out. I am highly interested in contributing some ideas to the project. Best

**Comment by michaeltcoelho** [comment]
@italolelis (sou sim man, isso ae hahaha) what @mariomazo has recommended is that i clone my fork at `hellofresh/janus` and inside my cloned folder `janus` i add `hellofresh/janus` upstream url? I'll have two janus project, one is my fork.

**Comment by italolelis** [comment]
Hi, @mariomazo!

Oh, if you are in Berlin we could go for lunch or coffee anytime this week or next, wdyt? We could discuss some ideas for the project for sure.
Feel free to reach me by email `il@hellofresh.com`.
