### ISSUE TITLE
Basic authorization configuration

### ISSUE THREAD

**Issue by sefasenturk95** [motiv-labs/janus#184]
Hey,

Thanks for developing this awesome gateway. It was very easy to configure but I'm stumbling upon an issue and I hope that maybe someone here can help me with it. 

Currently, I have a micro service running where users can authenticate via a POST request /authenticate. This endpoint will return a token which the user has to send with it when he does authenticated requests to other endpoints. The requests will have a Authorization header which will include for example `"Basic 58ccd028e3ca417829a62d57da1253229f03cca4da8ea2df15dd3ac4cb426c21"`. In this micro service there is also an endpoint named /validate to validate the token via a POST request.

I know there is a plugin named authorization included for basic authorization. Unfortunately, in the documentation, I can't find how to implement/configure this in the gateway. Can any one point me in the right direction?

Thanks in advance!

**Comment by italolelis** [comment]
Hello @Sef1995,

Yes, we were supporting basic authentication out of the box, but due to a bug in the chosen package, we removed it. I'll add the basic authentication plugin again pretty soon and also add documentation on how to use it.

Sorry for this inconvenience.

**Comment by sefasenturk95** [comment]
Hi @italolelis,

Thanks for your response. Do you have any idea when this will be added again?

**Comment by italolelis** [comment]
I plan to implement this by next week

**Comment by sefasenturk95** [comment]
OK, thanks!

**Comment by italolelis** [comment]
Implemented on #185
