### ISSUE TITLE
It is possible to change the default password?

### ISSUE THREAD

**Issue by kairotavares** [motiv-labs/janus#187]
Hi,

I would like to know if there is some way to deploy Janus with an mongodb and store the password there, allowing it to be altered by the admin using the APIs?

**Comment by italolelis** [comment]
Hi @kairotavares,

Do you mean password for the Admin API? Or passwords that will be checked before the proxy to the upstream happens?

If you are talking about the Admin API login, this week I'm releasing a new feature where you will be able to login to the Janus Admin API with your github account, limit access by organization/team/users or you'll be able to use the normal provider where you can define a password that will be checked when you try to login to the admin api.

**Comment by italolelis** [comment]
I'm closing this for now since it was addressed on #188. Feel free to reopen it if you think it's necessary
