### ISSUE TITLE
Add new route to janus

### ISSUE THREAD

**Issue by michaeltcoelho** [motiv-labs/janus#189]
Hi there,

I'd like to add a custom route to janus. By seeing oauth2 plugin as an example for building one it got very complicated to understand, i'll have to add a `loader.go` to my plugin and make some logic. Is there a better way of doing that?

**Comment by italolelis** [comment]
Depends on what your route will do. You'd like to add a custom route to Janus Admin API? 
If yes, then you should look here https://github.com/hellofresh/janus/blob/master/pkg/web/provider.go#L60

The oAuth2 has a loader because we need to load all the configurations for OAuth and generate routes in runtime for it. I don't think that's your case.

**Comment by michaeltcoelho** [comment]
Hey @italolelis (sou Brasileiro sim, sou da região de São Carlos - SP). 

I'd like to add something like `http://janus:8080/signup/` not an admin route exactly. I'll take a look at what you've suggested.

**Comment by italolelis** [comment]
Ah but that route will just be another proxy... right? If it's a proxy then you just need to add a proxy like the [Quick Start](https://hellofresh.gitbooks.io/janus/quick_start/add_endpoint.html) says. I'm sorry but I don't know what you are trying to achieve/do :/

**Comment by michaeltcoelho** [comment]
When signing up a new user on my app i have to create a user on my auth service and send its data to my other subscription service. I'd like to add a route to send a post to my auth service and then, with its response merged with post data, send it to my subscription service. I'd like to do it on api gateway layer.

**Comment by italolelis** [comment]
Ahh now I understand. I would simply write a plugin to achieve that, It's probably waaay simpler than trying to figure out the routing registering flow.

**Comment by italolelis** [comment]
I'm closing this issue since I think the question was answered. Feel free to reopen it if it's still a problem
