### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by sefasenturk95** [motiv-labs/janus#192]
Hi there,

I forked the project and made some changes. But when I try to build the project I get this error:
```
$ make all
==> Cleaning project
==> Installing dependencies
==> Building... 
Building application version 0.0.1-dev
Building default binary
# github.com/hellofresh/janus/pkg/jwt/provider
../../hellofresh/janus/pkg/jwt/provider/provider.go:9: undefined: sync.Map
../../hellofresh/janus/pkg/jwt/provider/provider.go:12: undefined: sync.Map
../../hellofresh/janus/pkg/jwt/provider/provider.go:27: undefined: sync.Map
make: *** [build] Error 2
```

Any idea how to fix this? I already tried removing all dependencies from my GOPATH and downloading them again.

Thanks!

**Comment by michaeltcoelho** [comment]
Hey @Sef1995 , what is your go version? I think you're on 1.8, try updating it to 1.9. :)

**Comment by sefasenturk95** [comment]
Hi @michaeltcoelho,

Thanks for your reply, I just found that out myself haha.

**Comment by michaeltcoelho** [comment]
@Sef1995 nice!

@italolelis we should put go version as a requirement on the docs, what do you think about?

**Comment by italolelis** [comment]
@michaeltcoelho Yes, you are right, let's put the go version as requirement 👍
