### ISSUE TITLE
Basic Auth middleware is not using a constant time compare function to check passwords

### ISSUE THREAD

**Issue by kcq** [motiv-labs/janus#194]
Line 35 in https://github.com/hellofresh/janus/blob/master/pkg/plugin/basic/middleware.go leaks timing information that can be used to "guess" the password value.

It's a good idea to use the ConstantTimeCompare function (crypto/subtle package).

**Comment by italolelis** [comment]
Hi @kcq,

Thank you for this report. I'll work on this as soon as possible, or if you'd like you can send a PR.
