### ISSUE TITLE
More than one Endpoint in a single file? 

### ISSUE THREAD

**Issue by gsigler** [motiv-labs/janus#204]
Is there anyway for me to put more than one api endpoint in a single file?

**Comment by italolelis** [comment]
Hi @gsigler,

At the moment we don't support this. This would be a simple change though, we could think about implementing this in the future, but feel free to send a PR with this functionality if you'd like.

**Comment by marcelnubi** [comment]
Hello,
I plan to work on this issue in the following days.
My idea is to use an unnamed json array of api.Definition and parse it on the file_repository.go

Question: Should a duplicate Definition name invalidate the whole file or be ignored(or something else)?

**Comment by italolelis** [comment]
Hello @marcelnubi,

I appreciate your help with that. I think we could ignore it, basically, if the definition is invalid or if it's duplicated we can ignore it and log that it was discarded.

**Comment by marcelnubi** [comment]
PR for this issue is @ #228

**Comment by italolelis** [comment]
Solved on #228
