### ISSUE TITLE
Load Balance Upstream Requests

### ISSUE THREAD

**Issue by italolelis** [motiv-labs/janus#209]
Currently, there is no way to load balance the upstream requests made by Janus. At HelloFresh we rely on HAProxy that does that for us. Ideally what we'd like to have is a possibility to have multiple `upstreams` and balance the request between them using the desired algorithm.

This will require some changes:

- [x] add extra configurations to support balancing on the `proxy.Definition`
- [x] create the supported balancing algorithms
- [x] change the `transport` implementation to support balancing

**Comment by aneshas** [comment]
Hi, is this issue still available :)

**Comment by italolelis** [comment]
Hi @tonto,

I'm sorry I forgot to update this issue... It was solved on #212
