### ISSUE TITLE
Missing documentation for auth type "introspection"

### ISSUE THREAD

**Issue by PepijnK** [motiv-labs/janus#210]
According to the auth doc, the token type can be set to JWT or "introspection", but what is meant with "introspection"? In our auth setup, tokens are validated by calling some internal service and I wonder if introspection is the way to route auth requests to this service.

**Comment by italolelis** [comment]
Hello @PepijnK,

Introspection comes from the [OAuth2 definition](https://www.oauth.com/oauth2-servers/token-introspection-endpoint/) of it. If you OAuth provider comply with the introspection RFC then yes Janus will use it to validate the token against that server on every request. Not all providers support oauth2 introspection.

RFC: https://tools.ietf.org/html/rfc7662

**Comment by PepijnK** [comment]
Sweet, so it's just about adding 
`"active": true|false`
to my current token-info endpoint.
Only thing missing now is how to tell Janus to use that endpoint for token introspection. I guess it's something like "endpoint":"url" 🤡

**Comment by italolelis** [comment]
Ah for that you just need to configure your api definition to use the oauth2 plugin, there you can tell which oauth2 server do you wanna use. 

Maybe this can help you out https://hellofresh.gitbooks.io/janus/quick_start/add_auth.html
