### ISSUE TITLE
Validate the Upstream URL on the Admin API

### ISSUE THREAD

**Issue by italolelis** [motiv-labs/janus#211]
Now that we deprecated the `upstream_url` we need to make sure that whenever someone creates/updates an API Definition, the Admin API returns an error saying `upstream_url is deprecated please use upstreams instead`.

**Criteria:**

1. Create or Update an API definition using `proxy.upstream_url`
2. The API should return a `400` HTTP code and a message `upstream_url is deprecated please use upstreams instead`

**Comment by mereba** [comment]
@italolelis Thanks for the input earlier today. The status here is that folks will be shown an error when they try to create a new proxy api with upstream_url, but can update without being shown the error. Now onto fixing the tests :)

**Comment by italolelis** [comment]
I'm closing this issue since I think it's resolved. Feel free to reopen it if you still have problems
