### ISSUE TITLE
Is there a way to enable plugin for all endpoint

### ISSUE THREAD

**Issue by alileza** [motiv-labs/janus#218]
Is there a way to enable plugin for all endpoint without adding for each proxy endpoint?

**Comment by italolelis** [comment]
At the moment plugins only work by API definition. 

The best way to achieve this behavior is to build a plugin that registers a middleware on startup event. This way you have a global middleware that will be enabled for every single request. But you need to have a way to turn it on and off, and for that, you'd have to use a global configuration.
