### ISSUE TITLE
Combine Redis libraries

### ISSUE THREAD

**Issue by italolelis** [motiv-labs/janus#220]
Currently, Janus has two different libs to work with Redis. That's not an ideal scenario, we'd like to use one of these libs:`github.com/go-redis/redis` and `github.com/garyburd/redigo/redis`.

**Comment by mahmoudhossam** [comment]
@italolelis I'd like to work on this.

It seems redigo gets more usage in the project, go-redis is only used in [this file](https://github.com/hellofresh/janus/blob/538f371f1d8c5073d507693139fe0c2fc2944848/pkg/plugin/rate/setup.go)

Do you want to change this file to use redigo instead and remove go-redis from the project?
