### ISSUE TITLE
Hot reload with MongoDB Storage

### ISSUE THREAD

**Issue by hocklo** [motiv-labs/janus#229]
Janus with Mongodb storage haven't a hot reload feature.

**Reproduction Steps:**

1. Run oficial docker image
`docker run -e STORAGE_DNS=redis://<my redis host>:6379  -e DATABASE_DSN=mongodb://<my mongo host>:27017/<schema>-p 8080:8080 -p 8443:8443 -p 8081:8081 -p 8444:8444 quay.io/hellofresh/janus`
2. Add an endpoint
3. Call "apis" I'll see the endpoint
4. Call the route
5. Route not found

**Expected behavior:**
1. Run oficial docker image
`docker run -e STORAGE_DNS=redis://<my redis host>:6379  -e DATABASE_DSN=mongodb://<my mongo host>:27017/<schema>-p 8080:8080 -p 8443:8443 -p 8081:8081 -p 8444:8444 quay.io/hellofresh/janus`
2. Add an endpoint
3. I call "apis" endpoint and I'll see the endpoint
4. I call the route
5. Access to the content

**Observed behavior:**
When I restarted the contained I can access to the new route without problems, but it isn't hot reload.

What I can do for add a new endpoint without restart the container ?
Can I have a hot reload with janus and mongodb storage?

**Janus version:** latest
**OS and version:** latest docker image

**Comment by italolelis** [comment]
Hello @hocklo,

Thank you for the report. Janus should do the hot reload if you tell it to use Redis as your shared storage system and mongo as your database. As I can see you are using env vars to tell that to Jauns. I'll have to debug it to see if there are any errors happening. 

I'll let you know once I check it. Thank you again

**Comment by hocklo** [comment]
Hello @italolelis ,

I'm thinking that maybe is not necessary use a redis storage for hot reload. For example Kong gateway have an scheduler job that check the database every 5seconds by default. I think that can be a good solution and the gateway won't depend of 2 storages(MongoDB and Redis).

Im waiting for your response,
Best Regards!

**Comment by italolelis** [comment]
@hocklo,

Yes, I agree, I hate the dependency on redis. I was thinking about the consensus protocol or gossip protocol, but honestly, if there is smth simpler, like the schedule that you mentioned I would rather go for that. 

So do you know how it works? It queries the DB every 5 secs and detects changes and reload its configs? Isn't this dangerous if it's the case?

Thank you for the feedback

**Comment by hocklo** [comment]
Hey @italolelis ,

The API object has a "active" boolean property, maybe launch a query to MongoDB isn't a problem, because this property will mark wich endpoints publish.

If you receive an error from MongoDB you won't modify your endpoints.

Other point is that if you call some query a lot of times, the MongoDB WireTiger will move this query in cache memory zone.

Regards!

**Comment by rafaeljesus** [comment]
@hocklo are you using `STORAGE_DNS=redis://...` or `STORAGE_DNS=memory://...`. I'm asking because we were facing this issue when using in memory storage implementation, it is fixed here https://github.com/hellofresh/janus/pull/237 https://github.com/hellofresh/janus/pull/238 however it only works with one machine. Can you test again pls?

In regards to the hot reload solution you shared with us, I really appreciated thanks, despite it is straightforward I don't think it is the most elegant, but it is very simple to implement, so something to consider 👍

**Comment by hocklo** [comment]
Hey @rafaeljesus ,
I tryed with redis and inmemory and only work for a single instance of janus gateway.

When you have more than a single janus instace this solution not work,

I have 2 instances of janus, the first instance listen to port 8080 and 8081 and the second instance listen the port 7080 and 7081.

When I create a new endpoint to 8081 and access it to 8080 port of first instance all works well, but if you try to access from 7080 port of second instance this solution doesn't work. The second node not refresh the endpoints.

Regards!

**Comment by rafaeljesus** [comment]
Hi @hocklo 

Yes I've mentioned here
> however it only works with one machine

We'll work on a solution for this as soon as possible

**Comment by rafaeljesus** [comment]
Hi @hocklo recently we've added the polling mechanism https://github.com/hellofresh/janus/pull/305 I am gonna close this issue fell free to reopen or open a new one, thanks
