### ISSUE TITLE
UI Improvements for Health Check page

### ISSUE THREAD

**Issue by JuricDavor** [motiv-labs/janus#231]
Please fix a list of following issues:

1. [Remove "Problems" from title]
2. [Adjust text for input "Search" area]
3. [Reduce size of clickable area for "Api Name"]
4. [Include a link to the "Edit API" view for that api ]

Screenshot attached:
https://prnt.sc/h79msi
**Expected behavior:**

Acceptance Criteria and requirements can be found in this ticket : https://hellofresh.atlassian.net/browse/CORE-2236

**Comment by italolelis** [comment]
Please address this on hellofresh/janus-dashboard
