### ISSUE TITLE
Adjust Error messages for Login, APIs definitions and Health check page

### ISSUE THREAD

**Issue by JuricDavor** [motiv-labs/janus#232]
[Adjust Error messages for Login, APIs definitions and Health check page]

**Reproduction Steps:**

1. [Login error message: Try to login with a Github user which is not authorised ]
2. [Create a new API page: Navigate to Apis definition > Create New API > Click on Save button without filling any input fields > Click OK button]
3. [Health check page:  Navigate to Health Check page > Refer to listed APi's description]

Screenshot attached:

http://prntscr.com/h79bq8
http://prntscr.com/h7956y
http://prntscr.com/h6y4gw

**Comment by ivanzusko** [comment]
- [x] 2. resolved [here](https://github.com/hellofresh/janus-dashboard/pull/157)

**Comment by rafaeljesus** [comment]
In regards to health check page https://github.com/hellofresh/janus/pull/233
