### ISSUE TITLE
Sending POST on existing oauth server does not fail

### ISSUE THREAD

**Issue by s4nji** [motiv-labs/janus#234]
Sending POST on existing oauth server does not fail

**Reproduction Steps:**
1. Send a POST request to create a new oauth server
2. Replay the same request

**Expected behavior:**
Request should fail, as the oauth server already exists.

**Observed behavior:**
Request is successful with `201 Created` response.
The existing configuration is replaced with the POST body of the most recent POST request.

**Reference**
https://github.com/hellofresh/janus-dashboard/issues/181

**Comment by rafaeljesus** [comment]
Thanks for opening the issue, we'll look into this

**Comment by s4nji** [comment]
Fixed with #235
