### ISSUE TITLE
API Endpoint name should be a slug

### ISSUE THREAD

**Issue by s4nji** [motiv-labs/janus#245]
Currently non-URL friendly characters can be used as API endpoint name. This is a problem as they wouldn't be accessible from `/apis/API_NAME` endpoint.

API endpoint name should be validated and matched against the following pattern:
`/^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$/`

#### Reference
https://github.com/hellofresh/janus-dashboard/issues/240

**Comment by al3rez** [comment]
https://github.com/hellofresh/janus/pull/268

**Comment by italolelis** [comment]
solved on #272
