### ISSUE TITLE
Valide a plugin struct

### ISSUE THREAD

**Issue by rjtch** [motiv-labs/janus#249]
i tried to add plugin to my api and also to my oauth server and i only gate a validation error. How can i make it validated. my request below
```
PUT /apis/alain HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MTI2NTc0MjMsImlhdCI6MTUxMjY1MzgyM30._NmN-qTzeNjR4pvVdt-c8MwWn-3OMivhokDNi0FQxYU
Connection: keep-alive
Content-Length: 165
Content-Type: application/json
Host: janus:8081
User-Agent: HTTPie/0.9.9

{
    "plugins": [
        {
            "config": {
                "limit": "5-M",
                "policy": "local"
            },
            "enabled": true,
            "name": "rate-limiting"
        }
    ]
}

HTTP/1.1 400 Bad Request
Content-Encoding: gzip
Content-Length: 74
Content-Type: application/json
Date: Thu, 07 Dec 2017 13:58:24 GMT
Vary: Origin

{
    "error": "name: non zero value required;proxy: non zero value required"
}
```

**Comment by italolelis** [comment]
Hey @rjtch,

That's probably happening because you are using the PUT method. According to how HTTP methods should work, when using a PUT you should provide the whole API definition. If you do that you won't get this error. 
We will also work on improving this error message that doesn't have much sense.

**Comment by rafaeljesus** [comment]
@rjtch @hellofresh/janus is going to support `Patch` endpoint pretty soon, stay tuned 😉
