### ISSUE TITLE
Passing user information to micro-services

### ISSUE THREAD

**Issue by olvlvl** [motiv-labs/janus#28]
Most recipe related payloads depend on the type of user requesting it. This is mostly because the API is used to administer entities from HQ, but also serve customer or public data. Of course, an HQ admin and a guest user won't receive the same payload when requesting the same entity, some properties are only served to admin users. Thus, we need to know what is the role of the user issuing a request to return the proper payload.

We believe we won't be the only one with this issue, managing subscriptions without user information is going to be tricky. Especially because customers can update their subscriptions, but admins too.

For performance and practical reasons, we'd rather not have to request a _user_ service, or fetch the user's role, or id, from a database. Since the gateway is already storing the authentication token, could it store information related to the user too, or retrieve it somehow?

The ideal would be to receive `X-User-Id` and `X-User-Role` headers:

```
DELETE /recipes/580f10c5b0a36033a0640022 HTTP/1.1
X-User-Id: 123
X-User-Role: admin
```

**Comment by olvlvl** [comment]
I was checking HQ code and I think we are not using OAuth scopes properly, here is the HQ query:

```
return self::createClient()->login(
    "password",
    Config::get('clients.hellofresh_apiv2.username'),
    Config::get('clients.hellofresh_apiv2.password'),
    Config::get('clients.hellofresh_apiv2.client_id'),
    Config::get('clients.hellofresh_apiv2.client_secret'),
    "public,customer",
    "DE"
);
```

It uses "public,customer" when it should be using "admin" or something. We rely on what's in bob database for roles to determine the permission when we should be using scopes. Here is Slack documentation about scopes: https://api.slack.com/docs/oauth-scopes. They use grants such as `channels:write` but also perspectives such as `user`, `bot`, or `admin`. We should only check bob's user on authentication than store the resolved scopes with the token, and only care about them.

**Comment by italolelis** [comment]
Solved with JWT

**Comment by olvlvl** [comment]
I can't find the user's role in JWT claims, is it in `metadata`? https://github.com/hellofresh/auth-service/blob/master/jwt/token.go#L17

**Comment by italolelis** [comment]
This is probably not beeing set by API-v2 when creating a new user... If that's the case then we will need to migrate all the users again and add their roles to it. But this is not related to the gateway, please open a ticket in our Jira Dashboard
