### ISSUE TITLE
Validate iss field in JWT

### ISSUE THREAD

**Issue by jzyinq** [motiv-labs/janus#282]
I have a case, where I need to distinguish jwt token issued by oAuth server from other jwt tokens.
It's for situation, where app is using jwt, but I don't want any other jwt token to be valid for requests passing gateway besides that one from oAuth.

By the docs Janus only validate `exp` and secret. 
Is there any way to validate `iss` field in Janus ? 

Something like this could be used to verify any other field that is present in JWT payload:
```
    "token_strategy": {
        "name": "jwt",
        "settings": [{
            "alg": "RS256",
            "key": "-----BEGIN PUBLIC KEY-----\n ... \n -----END PUBLIC KEY-----"
        }],
        "validate": [{
          "iss": "custom_issuer",
          "aud": "custom_audience",
          "custom_field": "custom_value"
        }]
    }
```

**Comment by italolelis** [comment]
@jzyinq Thanks for reporting this. At the moment we can't validate the `iss` field since we use the `jwt` library to validate that for us. We can definitely think of a way to make it more flexible (maybe the way you mentioned).

**Comment by quba** [comment]
It would be really convenient 👍
