### ISSUE TITLE
Support weight of 0 for upstreams

### ISSUE THREAD

**Issue by iMartyn** [motiv-labs/janus#283]
When rolling out in a staged fashion it is useful to have a backend with a 0 weight (defined but not accepting traffic)

**Reproduction Steps:**

1. add a service with two backends
2. set one to 0 the other to 100 (for instance)
3. push traffic to the service

**Expected behavior:**

The backend with weight 0 should get no traffic, the backend with 100 should get all and no errors appear in the log.

**Observed behavior:**

Error in the log : 
error: invalid backend, weight 0 given
message: Could not elect one upstream

**Janus version:** 3.6.0
**OS and version:** Linux, ubuntu 16.04

**Comment by italolelis** [comment]
Solved on #292
