### ISSUE TITLE
Routing won't work if methods field is not present in api configuration

### ISSUE THREAD

**Issue by jzyinq** [motiv-labs/janus#284]
By the docs:
https://hellofresh.gitbooks.io/janus/proxy/request_http_method.html

```
By default, Janus will route a request to an API regardless of its HTTP method.
```

Unfortunately if I remove `methods` array from api definition none of methods are accepted and I got a message:
```
{
    "message": "no API found with those values"
}
```

Just remove `methods` from example config to test it out.

Please fix this to state from documentation.

**Janus version:** latest docker image

**Comment by italolelis** [comment]
@jzyinq Thanks for reporting this. We will work on this a soon as possible
