### ISSUE TITLE
Localized URL's

### ISSUE THREAD

**Issue by PepijnSenders** [motiv-labs/janus#29]
For some of our projects we will need localized URL's, so different URL presentations going to the same service.

For example for our recipe page:

https://www.hellofresh.de/recipes/taboule-salat-mit-wurzigem-hallo-58342b3e4348d25f8d3183c2

We want the URL in germany to be:

https://www.hellofresh.de/rezepte/taboule-salat-mit-wurzigem-hallo-58342b3e4348d25f8d3183c2

And both of them should be proxied to the same service, this is of course possible at the moment, but adding all of them will be hard and time consuming.

I would recommend adding a new optional argument to the routes, something like country, and on every request you can map the domain to the specific country and prioritze the routes that have a matching country in its configuration. If none match, use the `default`.

**Comment by italolelis** [comment]
This is currently supported by setting different proxies to point to the same upstream. I'm closing this issue because of that.
