### ISSUE TITLE
Rate limit consumer definition

### ISSUE THREAD

**Issue by ionutzp** [motiv-labs/janus#290]
Hello all,

From the documentation:
>  If the API has no authentication layer, the Client IP address will be used, otherwise the Consumer will be used if an authentication plugin has been configured.

I don't understand how the consumer is defined or what the consumer is. Is it the sub field in a JWT?

**Comment by italolelis** [comment]
@ionutzp Thanks for reporting this. The documentation was outdated and now it's ok. We don't care about consumers anymore, if you enable rate limit it simply works now.
