### ISSUE TITLE
Push docker image to docker hub?

### ISSUE THREAD

**Issue by coolerfall** [motiv-labs/janus#291]
Hello，all
 I tried to install janus with docker, but I cannot pull image cause the GFW，could you please push docker image to docker hub? Thanks.

**Comment by italolelis** [comment]
Hi @Coolerfall,

Thanks for the heads up on that. Yes, we want to change to docker hub as soon as possible.

Once it's done I'll update this ticket.

**Comment by aleksandrzhiliaev** [comment]
Done in https://github.com/hellofresh/janus/pull/451
