### ISSUE TITLE
Missing examples: How to delete/update API endpoint configurations

### ISSUE THREAD

**Issue by kigen** [motiv-labs/janus#306]
I have been going through the [documentation](https://hellofresh.gitbooks.io/janus/) and it seems there's no example of how to:
1. Update endpoint configuration 
2. Delete endpoint config.

Unless I am looking at the wrong place: 
Guidance will be appreciated.

**Comment by vgarvardt** [comment]
Done in https://github.com/hellofresh/janus/pull/342
