### ISSUE TITLE
Error while adding a plugin to the gateway

### ISSUE THREAD

**Issue by kamiiiel** [motiv-labs/janus#310]
I followed your documentation for adding a plugin ([rate_limit](https://hellofresh.gitbooks.io/janus/quick_start/add_plugins.html)) but unfortunately I get an error saying 

```json
{"error":"name is required;proxy.listen_path is required"}
```

So it seems the gateway consider that as a new APi and not a plugin for an existing API.

Btw, Thanks for your very nice app.

**Comment by rafaeljesus** [comment]
@elitegit thanks for opening the issue we'll gonna take a look at it

**Comment by badaa** [comment]
Same error occurred!

**Comment by carolove** [comment]
Same error occurred

**Comment by s4nji** [comment]
That is correct @elitegit; when sending a `PUT` request, the api definition will be replaced with the definition in the request body.
The request would have worked if it were a `PATCH` request, however Janus doesn't handle `PATCH` requests, so it's a mistake in the documentation.
