### ISSUE TITLE
Configuration with mongo doesn't load api volume

### ISSUE THREAD

**Issue by sromerotech** [motiv-labs/janus#343]
When I configure Janus with mongo :
```
[database]
  dsn = "mongodb://janus-database:27017/janus"
```
files on `./apis:/etc/janus/apis` volume are not automatically loaded.

**Expected behavior:**

Api files should be read from volume like when janus is configured with 
```
[database]
  dsn = "file:///etc/janus"
```

**Janus version:** last
**OS and version:** linux ubuntu

**Comment by vgarvardt** [comment]
Current behavior is correct - you may have only one source of APIs - either filesystem or mongodb, mixed/multiple databases are not supported.
