### ISSUE TITLE
Access-Control-Allow-Origin header duplication when CORS enable on the service

### ISSUE THREAD

**Issue by Vxplus** [motiv-labs/janus#36]
When using the Gateway to request information a service which already handles CORS, the CORS in the Gateway and the Delivery Logistic Service is duplicating the Access-Control-Allow-Origin header which causes the following error:

**Reproduction Steps:**

1. Make request to any CORS supporting endpoint through Janus

**Expected behavior:**

No header duplication.

**Observed behavior:**
```
XMLHttpRequest cannot load https://end-point-url. The 'Access-Control-Allow-Origin' header contains multiple values 'url, url', but only one is allowed. Origin 'url' is therefore not allowed access.
```

**Comment by italolelis** [comment]
@Vxplus This is not a problem on the api gateway side, the service should not implement cors and let the gateway do it.
