### ISSUE TITLE
Is Janus still being actively developed?

### ISSUE THREAD

**Issue by allyraza** [motiv-labs/janus#421]
> Note: This project is in maintenance mode. There will be bug fixes, but no feature development

you guys not developing it anymore ? can I ask for the reason if you don't mind, we are using should we look for alternative ?

**Comment by s4nji** [comment]
Hello!

The short summary would be that it no longer makes a good business sense for us to keep developing and maintaining the project.
Internally, we are already deprecating and beginning to move away from Janus. I personally recommend [Kong][1], [Traefik][2], or [KrakenD][3] as alternatives to Janus.

[1]: https://github.com/Kong/kong
[2]: https://github.com/containous/traefik
[3]: https://github.com/devopsfaith/krakend

**Comment by ardityawahyu** [comment]
What makes you deprecating it? any technical reason for that? @s4nji

**Comment by s4nji** [comment]
> What makes you deprecating it?

For the same reason mentioned in my previous comment.

> any technical reason for that?

I couldn't think of any specific technical issue that pushed the decision to deprecate Janus. For the most part, we have been able to use and update Janus to suit our needs.

**Comment by luisfmelo** [comment]
Hi!

Just want to say that the work developed here was really good and I'm sad to read that Janus is being deprecated.

One final thought. There are a set of api gateways out there like the ones you listed but, a simple api gateway, easy to set up and use... Man that is difficult and Janus totally nailed it. 

I think that, there is only one thing that I think it would be a huge improvement: authorization per endpoint.

**Comment by jtesser** [comment]
As a followup here Motivlabs has taken the project over and is currently using, supporting and maintaining Janus
