### ISSUE TITLE
janus 3.8.18-10d2b39 (janus_windows-amd64.exe)

### ISSUE THREAD

**Issue by WillianBR** [motiv-labs/janus#430]
I'm trying to run "janus 3.8.18-10d2b39 (janus_windows-amd64.exe)" into "Windows 10 x64".
But always hit the same error.  I try it in _CMD.EXE_ and _x86_64-w64-mingw32_.

**Reproduction Steps:**

1. Downloaded <https://github.com/hellofresh/janus/releases/download/3.8.18/janus_windows-amd64.tar.gz>
2. Created a basic "**janus.toml**"
3. Started as "**janus_windows-amd64.exe start --config ./janus.toml**"

**Observed behavior:**

==> OUTPUT ERROR:

`time="2020-01-08T08:04:04-03:00" level=info msg="Janus starting..." version=3.8.18-10d2b39
[StatsGo] 2020/01/08 08:04:04 Stats counter incremented metric=app.init.ES9905-F9843094.janus__windows-amd64_exe
[StatsGo] 2020/01/08 08:04:04 Stats counter incremented metric=total.app
{"level":"info","msg":"Invalid or no stats exporter was specified","stats.exporter":"","time":"2020-01-08T08:04:04-03:00"}
{"level":"info","msg":"Invalid or no tracing exporter was specified","time":"2020-01-08T08:04:04-03:00","tracing.exporter":"None"}
Error: could not build a repository for the database: could not create a file system repository: open /etc/janus/apis: O sistema não pode encontrar o caminho especificado.
`

**Environment:**

```
$ stat /etc/ /etc/janus
  File: /etc/
  Size: 0               Blocks: 4          IO Block: 65536  directory
Device: 542d3607h/1412249095d   Inode: 1125899906971290  Links: 1
Access: (0755/drwxr-xr-x)  Uid: (197609/ Willian)   Gid: (197121/ UNKNOWN)
Access: 2020-01-07 13:36:34.681643700 -0300
Modify: 2020-01-07 13:36:34.681643700 -0300
Change: 2020-01-07 13:36:34.681643700 -0300
 Birth: 2019-12-18 10:57:58.133897500 -0300
  File: /etc/janus
  Size: 0               Blocks: 0          IO Block: 65536  directory
Device: 542d3607h/1412249095d   Inode: 1407374883759239  Links: 1
Access: (0755/drwxr-xr-x)  Uid: (197609/ Willian)   Gid: (197121/ UNKNOWN)
Access: 2020-01-07 13:41:49.071859600 -0300
Modify: 2020-01-07 13:41:49.071859600 -0300
Change: 2020-01-07 13:41:49.071859600 -0300
 Birth: 2020-01-07 13:36:34.681643700 -0300
```

**Janus version:** janus 3.8.18-10d2b39
**OS and version:** Windows 10 x64

Thanks!

[@WillianBR](https://api.whatsapp.com/send?phone=5561999881277&text=ABOUT%3A%20janus%203.8.18-10d2b39%20(janus_windows-amd64.exe)%20at%20https%3A%2F%2Fgithub.com%2Fhellofresh%2Fjanus)

**Comment by vgarvardt** [comment]
As I see from the output it is complaining that the path `/etc/janus/apis` is not found - this is the default path for file system based endpoints list. You can find some details at https://github.com/hellofresh/janus/blob/master/docs/quick_start/file_system.md
