### ISSUE TITLE
Question about params

### ISSUE THREAD

**Issue by nonils** [motiv-labs/janus#456]
Hi there. I have a question about if in janus we have a way to know or infer a request param. For example. If you have a uri like /example/{id} -> gets the id to do a custom action.
Thanks

**Comment by vgarvardt** [comment]
If I got your question then you're talking probably about _Named url parameters_ described at https://github.com/hellofresh/janus/blob/master/docs/proxy/routing_capabilities.md

**Comment by nonils** [comment]
Yes thanks. And just in case I want know what is the handlers that you use to handle the request if I can know

thanks in advance

**Comment by vgarvardt** [comment]
If you're talking about router - internally `github.com/go-chi/chi` v3 is used currently - https://github.com/hellofresh/janus/blob/master/go.mod#L19

**Comment by nonils** [comment]
Thanks 👍
