### ISSUE TITLE
Configuration files

### ISSUE THREAD

**Issue by olvlvl** [motiv-labs/janus#83]
Instead of storing endpoints configuration in MongoDB, I'd like to use files like nginx or Apache do, in a `/etc/janus` directory, with possibly _enabled_ and _available_ directories.

**Comment by italolelis** [comment]
Can you develop more on this thought? 
It is something that we pretend to implement at some point, but I would like to understand technically why do you prefer to use files?

**Comment by olvlvl** [comment]
Files can be versioned, I guess you can argue that Mongo documents can be versioned too, but I'd rather deploy a bunch of files in a directory than having to make a HTTP request to create a token, than several others to create/update the documents. Besides the cost of reading files is nil compared to the cost of establishing a connection to Mongo and requesting documents.

Also, I would feel better if the gateway was not accepting incoming requests to configure it, doesn't seam safe to me.

**Comment by italolelis** [comment]
Closing this because it was implemented on #101
