### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by move-city** [motiv-labs/janus#84]
I was following the instructions of the readme, copy the docker-compose from the example,
then i get the token and post the json in the example, but I get a 404 error.

In the root I got "Welcome to Janus, this is version 1.0"

First i tried with my own microservice endpoint, and it doesn't work, i think it was for the docker-compose network, then, i tried with the example, and also fails.

Any idea what I'm doing wrong?

**Comment by italolelis** [comment]
This is probably due a change that we did, at the moment the gateway is not hot reloading the configurations, we are building smth that will do this in a better way. Did you try to reload the gateway after you registered your API?

**Comment by move-city** [comment]
@italolelis thanks! just restart the containers and all the routes now works!
