### ISSUE TITLE
Credentials in target_url are ignored and not presented to upstream as Authorization: Basic header

### ISSUE THREAD

**Issue by drauschenbach** [motiv-labs/janus#96]
If an upstream (target_url) requires Basic Auth via a statically provisioned API KEY or similar thing, it is customary to be able to provide the credentials in the URL, and for the user agent to detect the userInfo in the URL and to move it over to an `Authorization: Basic <base64(userInfo)>` header.

Curl is an example of this, and it allows you to use either of 2 forms to set an Auth Basic header:

1. `$ curl -u user:password http://myhost:port`
2. `$ curl http://user:password@myhost:port`

**Reproduction Steps:**

1. Register an API with /myRoute/* ==> http://user:password@upstream
2. Restart Janus (issue #95 workaround)
3. Attempt to access http://janus/myRoute. Get 401 Unauthorized

**Expected behavior:**

Upstream would be presented with Authorization: Basic header  and would authorize.

**Observed behavior:**

Upstream returns 401 Unauthorized which means it was not presented with an Authorization: Basic header.

**Janus version:** [1.7.4-rc.6](https://github.com/hellofresh/janus/releases/tag/1.7.4-rc.6)

**Comment by italolelis** [comment]
Implemented on #185
