### ISSUE TITLE
Wrong format for updated_at

### ISSUE THREAD

**Issue by olvlvl** [motiv-labs/janus#98]
The `updated_at` property of `api_specs` items has a wrong format e.g. `-62135596800000` instead of something like `2017-01-20 11:03:17.331Z`.

**Expected behavior:**

`updated_at` should be ISO.

**Observed behavior:**

`updated_at` is not ISO.

**Comment by vgarvardt** [comment]
Where did you find this?

**Comment by italolelis** [comment]
Since we don't have the `created_at` and `updated_at` fields anymore on version `2.0` onwards I think this can be closed.
If we introduce the time fields back then we should have this point in consideration.
