### ISSUE TITLE
Use a handle instead of MongoID to reference the oauth server

### ISSUE THREAD

**Issue by olvlvl** [motiv-labs/janus#99]
`api_specs` would be easier to read and define if the `oauth_server_id` value was a human readable value such as `api_oauth` than a MongoID such as `ObjectId("5834110db1c3754274e64f0e")`.

**Comment by italolelis** [comment]
But then we would have to have another unique field on the `api_oauth` collection to reference here... like a `slug`, we could definitely do something like this, since we are moving towards file-based configurations as well, this would help to link them together.
